### ISSUE TITLE
Crash when fluidlogging a block of material water

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Fluidlogged-API#112]
**Describe the bug**
I'm not sure if this is still the same issue as the #111, but I rather opened a new one.
The issue is still interconnected with my mod: [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery). So I tried to find out if it's actually not my fault, but however I tried, it still did crash.

**To Reproduce**
Same as the #111

**Logs**
[Latest Log](https://gist.github.com/juraj-hrivnak/aa22dae04d465c6f3769f0f9adba1aa9)
[Client Crash Report](https://gist.github.com/juraj-hrivnak/21630346cdb6fc14a742db94a30b7f9f)
[Server Crash Report](https://gist.github.com/juraj-hrivnak/01bd6e6b55e5e157bdc049a6ce74ce91)

**Comment by jbredwards** [comment]
This is a different crash. The only way I was able to recreate it was by using `/setfluid ~ ~ ~ "modded_fluid"` on one of your blocks. Removing the `IFluidloggable` implementation should fix it (though you may also have to create a new world since old blocks will still be fluidlogged), fluid blocks should never implement it cause it results in fluidlogged fluids which are dangerous. If you want the blocks permanently waterlogged extend the `BlockWaterloggedPlant` class or use a similar implementation of `IFluidloggable`, just make sure not to use `Material.WATER`. If you have any more questions about the api feel free to start a discussion so other people with the same questions can easily find the answers, until I get around to finishing the wiki anyway 😅
