### ISSUE TITLE
Crash with Betweenlands v3.9.0 and above.

### ISSUE THREAD

**Issue by magcicada** [jbredwards/Fluidlogged-API#144]
Fluidlogged-API and other change fluid behavior will cause this crash, the developers of Angry-Pixel has not responded yet, just report here that let you to look about it and mark it to here, the issue can find aat here:
https://github.com/Angry-Pixel/The-Betweenlands/issues/1343

**Comment by Rongmario** [comment]
SmoothWater isn't needed if Fluidlogged-API is installed.

**Comment by magcicada** [comment]
It just only use Fluidlogged-API or SmoothWater such one mod with Betweenlands and get crash, this is the error on the Betweenlands side, not here. just mark this issue to here.

**Comment by jbredwards** [comment]
Try running the game without Fluidlogged API (just to make sure the issue is in fact caused by this mod), I tried running just Fluidlogged API with Betweenlands v3.9.1 and things worked fine. Also don't use Smoothwater alongside MAGE, since Smoothwater is just a deprecated version of MAGE with less features.

**Comment by magcicada** [comment]
it fixed in the dev.
