### ISSUE TITLE
Fluidlogged makes some blocks unplaceable

### ISSUE THREAD

**Issue by AechtRob** [jbredwards/Fluidlogged-API#152]
Some blocks in our Prehistoric Nature mod are not placeable when the FluidLoggedAPI mod is installed. I'm not sure what information about our mod's code you need to be helped to deal with this, or to help me know if I can fix something at our end. The blocks in question when placed place multiple blocks in the world as a multiblock structure and some of these blocks contain a tile entity. The placement is handled in onBlockAdded.

**Comment by jbredwards** [comment]
`BlockOligopoolMachine` makes a bad call to `isReplaceable` within the `canPlaceBlockAt` method on line 113. This can be fixed by changing `this.isReplaceable(worldIn, pos.up())` to `super.canPlaceBlockAt(worldIn, pos.up())`.

Normally this would be fine, but the reason the old code breaks while Fluidlogged API is installed is that it changes `Block#isReplaceable` to not call `getBlockState`, which fluidlogged api does this to increase performance (since the block that calls the method is usually always the block at the position, see `BlockSnow` for example which crashes if the block there isn't a snow layer)
