### ISSUE TITLE
Placing sponge also removes fluidlogged blocks 1.12.2

### ISSUE THREAD

**Issue by KenyMylankca** [jbredwards/Fluidlogged-API#2]
yeah it is
i mean it should remove only the fluid
reproduce management:
1-placed oak stairs
2-right click it with water bucket
3-place a sponge near to it
Result: oak stairs gone with the water.

**Comment by KenyMylankca** [comment]
and also fence gates can't be waterlogged?...

**Comment by KenyMylankca** [comment]
and why it doesn't work for chests?

**Comment by jbredwards** [comment]
-Good catch with the sponges, I forgot those were in the game lol. That issue will be fixed next update.
-I didn't do fence gates back in Not Just Another Ruby Mod 2 because I was worried about mod incompatibility. Looking back, I don't think there would be any, so I'll add it next update.
-No tile entities can be fluidlogged because of how I implemented the mechanic (look at the source code to see more about this). Other mods can make their tile entities fluidloggable with some extra work, however I won't make vanilla ones fluidloggable, as doing so would require me to rewrite all of their classes, which would break tons of mods.

**Comment by KenyMylankca** [comment]
thanks a lot for the explanation.

**Comment by jbredwards** [comment]
the issue with the sponges has been fixed in v1.2, and default support for fence gates has also been added in v1.2

**Comment by KenyMylankca** [comment]
that's awesome!

**Comment by KenyMylankca** [comment]
hey uhm, it crashes when i use sponge near a modded fluid. hope u can fix it. heres the crash log
[crash-2021-05-26_00.46.55-server.txt](https://github.com/jbredwards/Fluidlogged-API/files/6542554/crash-2021-05-26_00.46.55-server.txt)

**Comment by jbredwards** [comment]
fixed in v1.3

**Comment by KenyMylankca** [comment]
great job! thanks
