### ISSUE TITLE
 Doesn't work with mcreator?

### ISSUE THREAD

**Issue by salitamax** [jbredwards/Fluidlogged-API#210]
I would like to create the update plants, and other varieties, 
but it seems that it does not work with the mcreator block, 
it does work with the fences, walls, leaves and trapdoors,
 but not with the solid block or the customizable .json

**Comment by jbredwards** [comment]
> I would like to create the update plants, and other varieties

If that's all you're doing with MCreator, I recommend looking into [Greenery](https://www.curseforge.com/minecraft/mc-mods/greenery) (a mod that adds underwater and surface plants, and lets you add your own!)

> it seems that it does not work with the mcreator block

How are you making your blocks fluidloggable? If you're using json, make sure its file path matches `assets/#your_mod_id#/fluidlogged_api/whitelist.json` (otherwise fluidlogged api won't see it). If it still doesn't work, send me your `whitelist.json` file so I can check that it's valid. If you're using `IFluidloggable`, can you post your block's code?

**Comment by salitamax** [comment]
I'm sorry, I don't know about programming, the .json files are from blockbench that I use for mcreator,

Thanks for the suggestion but...I was testing Greenery and it crashed with other mods I have.

**Comment by jbredwards** [comment]
Oh ok, let me start at the beginning then 😅.

To start off, if you're wanting to add support into your mod itself, it needs to tell Fluidlogged API which blocks you want fluidloggable. This can be done through json files (no programming required!). My seared ladder backport mod adds Fluidlogged API compatibility this way, so you can use that mod's json file (linked [here](https://github.com/jbredwards/Seared-Ladder-Backport-Mod/blob/1.12.2/src/main/resources/assets/searedladder/fluidlogged_api/whitelist.json)) as an example. Firstly, create a new folder named `fluidlogged_api` in your mod's `assets/#your_mod_id#` folder. Fluidlogged API automatically scans this folder at runtime to look for any whitelist entries your mod might specify. To specify whitelist entries, create a new file named `whitelist.json` in your `fluidlogged_api` folder (this one file will contain all of your mod's whitelist entries). For more info about this, read Fluidlogged API's [config wiki](https://github.com/jbredwards/Fluidlogged-API/wiki/Config#whitelist). If you run into any difficulties, don't hesitate to ask for help :)

But if you're just wanting to use your config, and are having issues with it not working, could you send it to me so I can check that it's valid?

**Comment by salitamax** [comment]
hehe, yes it works, thanks for the help
