### ISSUE TITLE
Conflict with TerraFirmaCraft: TNG

### ISSUE THREAD

**Issue by Lylythii** [jbredwards/Fluidlogged-API#37]
**Describe the bug**
Fault is no-doubt on TFC's end, felt I should report it to both.

Fluidloggable blocks cannot be fluidlogged with TFC fluids using TFC buckets.
Attempting to fluidlog a block using TFC fresh/salt/hot water or Vanilla water, using a TFC bucket, will delete the block/replace it with the fluid.
[doesn't appear to occur with other TFC fluids like limewater or molten metals]

**To Reproduce**
- Place a fluidloggable block.
- Take a TFC bucket & attempt to fill said block. [block will be placed on the side of the block, rather than in the block]

- Place a fluid.
- Place a fluidloggable block inside that fluid.
- Attempt to fill said fluidlogged block with a TFC fluid. [block will be repalced]

**Expected behavior**
- Blocks should not be replaced.
- Fluids from TFC buckets should place inside fluidloggable blocks.

**Video**
https://youtu.be/tBRzlzhcj1I

**Comment by Lylythii** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1818

**Comment by jbredwards** [comment]
This mod uses [FluidUtil#getFluidHandler](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L484-L495) to determine if an item is holding a fluid (ie a water bucket), or if the item can collect a fluid (ie an empty bucket). The TNG mod's bucket item doesn't seem to properly use the forge capabilities for mod compat, which means this issue is coming from their side.
