### ISSUE TITLE
Crash on startup, Java fails to start

### ISSUE THREAD

**Issue by Smellslikeoranges** [jbredwards/Fluidlogged-API#38]
I'm not entirely sure what is the causing the problem, but as soon as the startup process starts to register Fluidlogging API, LaunchWrapper reports that it's unable to launch.

I'm using version 1.6.2

https://paste.ee/p/3ojVU

**Comment by jbredwards** [comment]
According to the crash log, it would seem you have two instances of fluidlogged api installed (along with some other duplicate mods). Try removing those and let me know if that helps.

**Comment by Smellslikeoranges** [comment]
Actually, one of those two instances of fluidlogged api (1.5.2) was disabled, I was testing earlier to see if the crash was specific to the current version. It wasn't I'm afraid.

The other duplicate mods are also disabled.

**Comment by jbredwards** [comment]
does [this](https://github.com/jbredwards/Fluidlogged-API/files/7255746/extract.me.zip) fix your issue? The next version of this mod is planned to have built-in vanilla tile entity support, but that won't be out for a while.

**Comment by Smellslikeoranges** [comment]
Thanks for the attempted fix. It got much farther through the start-up process, but it did still crash when it was registering the "BlockRailBase" it looks like.

https://paste.ee/p/hSisO

**Comment by jbredwards** [comment]
how about [this](https://github.com/jbredwards/Fluidlogged-API/files/7255819/extract.me.zip)? I did this in earlier versions, but if I recall correctly, this gave someone else problems so I changed it.

**Comment by Smellslikeoranges** [comment]
It crashed again, a little bit earlier this time, I can't really identify why from the log.

https://paste.ee/p/bC1yV

**Comment by jbredwards** [comment]
[extract me.zip](https://github.com/jbredwards/Fluidlogged-API/files/7255925/extract.me.zip) third time's the charm I hope lol. If this doesn't work, then I'll work on this tomorrow, getting late here

**Comment by Smellslikeoranges** [comment]
Sadly, it did crash again. Oh well, we tried. Thanks again for all your help.

At any rate, I'll still post the log for later reference: https://paste.ee/p/NwHYb

Have a good night!

**Comment by jbredwards** [comment]
[this](https://github.com/jbredwards/Fluidlogged-API/files/7261331/extract.me.zip) simply removes the transformation that seems to be causing all this. If it still doesn't work, then it's possible the issues are caused by something else another mod is doing.

**Comment by Smellslikeoranges** [comment]
Having just tried it, it did crash again, so I'm definitely in agreement that a separate mod is probably causing it. 

Sorry for all the trouble, I wish I had a good way of telling which one is acting problematic. :/

**Comment by jbredwards** [comment]
If I were you, I'd test to see if the crash occurs without any instance of fluidlogged api installed, just to be truly sure the crash doesn't relate to it (if you haven't already). There are two things outside the mod that catch my eye. The first thing is something called "Meson ASM" at line 988 in the crash log. It seems to cause the crash. I tried looking up the mod, but found nothing, do you know what it is? The second thing is that you're using optifine E3, which is made for forge v2795 Try updating optifine to G5 and see if that does anything.

Edit: G5 is made for forge v2847. So even if updating optifine doesn't help, backporting forge may be worth doing. I know for myself I prefer working with forge v2847, since the versions that come after mess up how asm is handled in a dev workspace. The forge version alone may even be causing the crash with some other mod that's made for the earlier versions ¯\_(ツ)_/¯

**Comment by jbredwards** [comment]
closed due to inactivity, reopen if not resolved
