### ISSUE TITLE
issues with block rotation in structures

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#39]
so ive been editing some structures that spawn underwater, i have edited every block within the structure to be fluidlogged and then saved the structure. when said structures get rotated during generation, the fluidlogged blocks dont get rotated.

just to confirm these are vanilla structures
![image](https://user-images.githubusercontent.com/603338/138320279-c5ab4abb-ee48-48d4-aad9-9708b758532f.png)

i have tested importing the same structure and rotating it and does seem to be an issue there too and not just during generation
for example, what this boat should look like from the front
![image](https://user-images.githubusercontent.com/603338/138320840-fff67909-27fb-42bc-8b74-58676f6d7d6e.png)

what happens when its rotated
![image](https://user-images.githubusercontent.com/603338/138320975-c133d5b4-a033-4aa9-b5bb-8190b9d9e6be.png)

**Comment by jbredwards** [comment]
Since the contained block is stored in a tile entity, this can't be fixed unfortunately. The methods used for block rotation & mirroring don't take in iblockaccess or blockpos, causing the tile entity to be inaccessible.

Some good news though, I am working on rewriting this mod from scratch (this should be visible outside the main branch). There are a lot of core problems & hardcoded limitations created by the way I handled fluidlogging before (no tile entity fluidlogging, many block rewrites, and the stored block being inaccessible for some methods (leading to some inconsistencies in-game). The new system will store the fluid in chunk capabilities, rather than storing the block in a tile entity! This will free up tile entities & allow them to be fluidloggable! This will also allow block whitelist & blacklist configs to be possible (since the fluidloggable blocks will no longer require massive asm changes to make them work)! This will also built-in fix your issue, along with a whole bunch of other small inconsistencies. :)

**Comment by xemnes** [comment]
oh nice! eagerly waiting for that then. does this mean any block can be fluidlogged and not just the vanilla block shapes?

**Comment by jbredwards** [comment]
Yes, you'll be able to add any block you want to the configs! Just wouldn't recommend adding fluids to the list (waterlogged water blocks) lol

**Comment by xemnes** [comment]
thats amazing, cannot wait. theres so many blocks i plan on adding to said list

**Comment by jbredwards** [comment]
fixed in v1.7, sorry for the wait!

**Comment by xemnes** [comment]
awesome! thank you. sadly im currently unable to test for a few weeks since my computer is in for repair.
