### ISSUE TITLE
Biomes O' Plenty Issues

### ISSUE THREAD

**Issue by whatsapp2** [jbredwards/Fluidlogged-API#54]
Well this bug was discovered when I generated a new world with Biomes O' Plenty installed, as soon as I spawned, my tps went crashing down and stoped at around 0.636. I scanned the area with LagGoggles mod, the scans showed that there was a massive amount of entities dropped near me: "item.tile.seaweed.kelp" to be precise, I searched around the world for a bit and it turns out I spawned near a BoP kelp forest. 
BoP uses a pseudo water logging for it's sea weed as far as I know and having this mod installed interferes with the placement of seaweed, kelp basically pops out as an item as soon as the block is placed on water

Edit: It also happens with other BoP water logged blocks like corals and algae

1. Generate a New World with BoP installed
2. Press T and paste this command "/bop tpbiome biomesoplenty:kelp_forest"
3. You might be lucky and it'll teleport you to a kelp forest where you'll immediately see the seaweeds pop out as an item and lag your client

Ran the /forge TPS as soon as I got close to the biome
<img width="709" alt="Captura de Pantalla 2022-03-18 a la(s) 17 27 22" src="https://user-images.githubusercontent.com/25994176/159096539-9389a916-9958-498e-a409-4f35fd044a6c.png">

If you need additional info or logs just let me know and I'll post my things asap

**Comment by Carvercarver1** [comment]
If possible, could the same fix be made as an option in case any other mod which adds similar things does that? Like "waterfix - <insert additional mods>" so it will automatically apply the fix by the same scheme, since the same bug happens with coralreef mod corals and oceanic expanse kelp (latter has two stages of issue: if added to whitelist, BOP-like issue happens. If not added, it renders flowing water at it's sides, which is the same issue kinda as they use their own waterlogging method for such blocks and API does not register such blocks as fluidloggable by itself. It DOES fluidlog them, rarely, but BOP drops issue happens and in my case even causes a crash due to entity ticking due to amount of drops). 

Unless the coming fix is done on part of API itself to remove the possible headaches for the future..

**Comment by jbredwards** [comment]
>If possible, could the same fix be made as an option in case any other mod which adds similar things does that? Like "waterfix - " so it will automatically apply the fix by the same scheme, since the same bug happens with coralreef mod corals and oceanic expanse kelp (latter has two stages of issue: if added to whitelist, BOP-like issue happens. If not added, it renders flowing water at it's sides, which is the same issue kinda as they use their own waterlogging method for such blocks and API does not register such blocks as fluidloggable by itself.

The `FluidloggedUtils.getFluidFromBlock` method's lack of material support was the problem, so I probably won't do this.

**Comment by Carvercarver1** [comment]
So it should fix same related issues, if I guessed right? Because on older versions of API it did work, though.

**Comment by jbredwards** [comment]
fixed in v1.7.1
