### ISSUE TITLE
Fluidlogged-API-v1.7.1b-mc1.12.2.jar Airwall bug with the Pistons

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#64]
Hi,
with your newest Update 1.7.1b of your Mod with the Pistons have I found a Air Fluid Bug. Look the Picture. 
The Pistons was okay then I place it.Then I the Pistons activate then give it by this Problem the 1 Piston was activate the other not and the left Piston have a Air wall. Then we now activate the second piston and deactivate the second pistons then deleted the air wall and the first piston is on all sides with water or we place water and then is it okay. The Picture 3 and 4 then we place it other and active the piston have airwalls but we can only replace the airwall with a bucket of water. I have make a video for you. I hope it is with the Pictures good to see it and can help you to fix the Air wall problem.

Link Youtube Video of the Bug:

https://www.youtube.com/watch?v=eUwh3rbRUUc

Picture:

![2022-03-23_19 45 44](https://user-images.githubusercontent.com/42325138/159774024-bb441f57-6361-43ab-8deb-332da6f062c2.png)
![2022-03-23_19 45 48](https://user-images.githubusercontent.com/42325138/159774038-6e6a5427-fe29-4820-ba90-599be2e648e7.png)
![2022-03-23_19 46 53](https://user-images.githubusercontent.com/42325138/159774041-dfef917b-9278-4d7f-a7a7-2d78cc89e375.png)
![2022-03-23_19 47 05](https://user-images.githubusercontent.com/42325138/159774043-ef414554-1ed0-4221-9c38-43e682c19873.png)

**Comment by jbredwards** [comment]
Believe it or not, that's just a weird side effect of an intentional mechanic. When water tries to fill a fluidloggable block by flowing into it, it checks if there's another source block horizontally around it that can also flow into it. For the cases of the screenshot, the check failed, so the pistons didn't get fluidlogged. Though this did inspire me to add vertical checks, which'll be added next update

**Comment by jbredwards** [comment]
added behavior in v1.7.2
