### ISSUE TITLE
Crash when flying around with Fluidlogged API, crash continues when re-loading world

### ISSUE THREAD

**Issue by Luke616** [jbredwards/Fluidlogged-API#75]
**Describe the bug**
Crash occurs randomly when flying around a world, then crash re-occurs when re-entering the world. Uninstalling Fluidlogged API causes the crash on load to stop occurring. This is likely some sort of mod interaction - was hoping you would have some insight as to what is causing the crash as the crashlog is not very descriptive.

Please let me know if you need any assistance squashing this - I can provide a link to the modpack and the testing world where the crash occurs on load.

**Crash Report:**
[crash-2022-03-28_17.04.17-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8366384/crash-2022-03-28_17.04.17-client.txt)

**Full Log:**
[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/8366379/latest.log)
.
**Versions used:**
Fluidlogged API v 1.7.2b
Minecraft Forge v 14.23.5.2860

**Comment by jbredwards** [comment]
Seems to be a conflict with phosphor, I'll see what I can do

**Comment by jbredwards** [comment]
does [this](https://cdn.discordapp.com/attachments/785959414632939571/958385622194741298/Fluidlogged-API-v1.7.2b-mc1.12.2.jar) fix your issue?

**Comment by Luke616** [comment]
I'm able to load into the world that had previously been crashing with that jar, so I think so. I'll keep flying around and testing to make sure it doesn't crop up again but we're probably good now

**Comment by Luke616** [comment]
Getting back in must have been a fluke - looks like it's still happening when flying around the world a bit

[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/8373794/latest.log)
[crash-2022-03-29_13.40.28-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8373795/crash-2022-03-29_13.40.28-client.txt)

**Comment by lovetothequeen** [comment]
Hi. I also have pretty much same or very similar issue on same versions of mod and same version of forge. So I will not describe crash and how it occurs, @Luke616 already described it.

I was playing with optimizing mods. ~~Actually, I deleted phosphor and problem still left there, and I think it's not just conflict or not the only conflictm, like it was always in that modpack.~~ Modpack used to make animation and it was always played on 12 chunks and since I actually now filming scenes on that modpack, I created random map trying to get maximum possible setting with 64 chunks and "ray-tracing" shaders at okay fps and probably only then noticed that problem.

I already used new fix you just dropped here in hope that it will help and I don't think it worked, maybe it load, further more? But I think it's probably only seems, still crashing anyway.

I found a "fix" to a problem and in order to do it, you need to open setting menu lower drawing distance, I had 64, I lowered to 12. And it's works just fine.  Any ideas why this could happen?

I clearly see there is something to do with ticks update too, like it updates slow?

Crash Report:
[crash-2022-03-29_22.50.18-server.txt](https://github.com/jbredwards/Fluidlogged-API/files/8374772/crash-2022-03-29_22.50.18-server.txt)

Full Log:
[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/8374773/latest.log)

Debug log:
[debug.log](https://github.com/jbredwards/Fluidlogged-API/files/8374927/debug.log)

Update:
Also very important note, it's still a problem related to phosphor. For some ankward reason that bug still be with you even after you uninstall phosphor until either you create new world or go to another world and only then it will work just fine.

And I will say that by testing phosphor without Fluidlogged on that modpack, game runs just fine.

**Comment by Rongmario** [comment]
Could Fluidlogging API be accidentally loading chunks in a cascading manner? (e.g not checking isAreaLoaded)?

**Comment by Luke616** [comment]
> I found a "fix" to a problem and in order to do it, you need to open setting menu lower drawing distance, I had 64, I lowered to 12. And it's works just fine. Any ideas why this could happen?

Interesting that changing the draw distance causes the issue to stop for you. I've been away from home doing packdev off an old laptop and have done all my testing with a draw distance of 6, so I can confirm it does happen at low draw distances as well.

**Comment by darkheadmaster132** [comment]
i have exactly the same problem but after few crashed the mod doesn't even load anymore

**Comment by jbredwards** [comment]
@darkheadmaster132 send your log

**Comment by juraj-hrivnak** [comment]
I have also the same issue. Here is the [latest log](https://gist.github.com/juraj-hrivnak/f1f62a775e88006a40ee411a5cf7fddc) and [crash log](https://gist.github.com/juraj-hrivnak/32acf85fec66c9ad4ba3ee6169991791).

It started to crash for me when I added some mods that generate the fluidlogged blocks.
Namely, it was Future MC and my fork of backported flora mod. [Here](https://github.com/juraj-hrivnak/underdog-flora/blob/8db3b6778f0ecb8855e59688771c738fd69896de/src/main/kotlin/azmalent/backportedflora/common/block/plant/freshwater/AbstractAquaticPlant.kt#L27-L28) I made the seagrass fluid-loggable, and that's why it crashes for me, I think.

Removing the Fluidlogged API or Phosphor fixes the issue.

**Comment by juraj-hrivnak** [comment]
> does [this](https://cdn.discordapp.com/attachments/785959414632939571/958385622194741298/Fluidlogged-API-v1.7.2b-mc1.12.2.jar) fix your issue?

I tried this version, and it still crashed. [Crash log](https://gist.github.com/juraj-hrivnak/48db6960edbb9b1531af4409cd5e6a86)

**Comment by jbredwards** [comment]
I've been flying around with [this](https://cdn.discordapp.com/attachments/785959414632939571/959963802793832488/Fluidlogged-API-v1.7.2c-mc1.12.2.jar) build & phosphor and I have yet to encounter the crash, perhaps it's fixed?
edit: the build is different from the one above, in case that wasn't clear

**Comment by Luke616** [comment]
> I've been flying around with [this](https://cdn.discordapp.com/attachments/785959414632939571/959963802793832488/Fluidlogged-API-v1.7.2c-mc1.12.2.jar) build & phosphor and I have yet to encounter the crash, perhaps it's fixed? edit: the build is different from the one above, in case that wasn't clear

Unfortunately still experiencing the crash with this version
[crash-2022-04-03_00.41.17-client.txt](https://github.com/jbredwards/Fluidlogged-API/files/8403829/crash-2022-04-03_00.41.17-client.txt)
[latest.log](https://github.com/jbredwards/Fluidlogged-API/files/8403830/latest.log)

**Comment by juraj-hrivnak** [comment]
Unfortunately, it is still crashing for me, either.
Try to reproduce it with just these mods:
- Fluidlogged API v1.7.2b or c
- [Phosphor Lighting Engine](https://minecraft.curseforge.com/projects/phosphor-forge)
- [Underdog Flora](https://www.curseforge.com/minecraft/mc-mods/underdog-flora) (mod that generates the seagrass)
- [SimpleDifficulty for Underdog](https://www.curseforge.com/minecraft/mc-mods/simpledifficulty-for-underdog) (dependency)
- [Shadowfacts' Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin) (dependency)

**Comment by Rongmario** [comment]
0.8.2 mixins, this line seems to be throwing a NPE:

https://github.com/SpongePowered/Mixin/blob/4585277f9f4b026065ce749f279ea1ad4919c4f1/src/main/java/org/spongepowered/asm/mixin/transformer/MixinConfig.java#L595

I also noticed that `MixinBooter` just isn't picking up the mixins to load them in? There should be a string of `Adding ... mixin configuration.` in the log but there isn't for Fluidlogged API...

**Comment by jbredwards** [comment]
@Rongmario I only started loading the mixins through MixinBooter last commit, so if you're using the curse release, that'd by why

**Comment by Rongmario** [comment]
Ah, I'm just looking through one of the logs here that's why

**Comment by gnomed-by-steve** [comment]
> @Rongmario I only started loading the mixins through MixinBooter last commit, so if you're using the curse release, that'd by why

Ah, poop. There's my culprit. Man, I need to start checking gits more often...

**Comment by gnomed-by-steve** [comment]
Alright, seems like loading mixins through mixinbooter fixed this issue.

Built the latest commit myself in powershell, gutted one of my old modpacks and ran just these 4 mods:
Fluidlogged API (latest commit), 
OptiFine (G6 pre-1),
Phosphor (0.2.7),
MixinBooter (4.2).

No crashes! Here's my [latest](https://github.com/jbredwards/Fluidlogged-API/files/8439865/latest.log), if there's anything silly in there, it's because my drive isn't the cleanest.

**Comment by Rongmario** [comment]
Seems like just a mixin application issue then, that's good news.

**Comment by jbredwards** [comment]
> Alright, seems like loading mixins through mixinbooter fixed this issue.

The issue still happens for me with the modlist provided by juraj-hrivnak
>- [Phosphor Lighting Engine](https://minecraft.curseforge.com/projects/phosphor-forge)
>- [Underdog Flora](https://www.curseforge.com/minecraft/mc-mods/underdog-flora) (mod that generates the seagrass)
>- [SimpleDifficulty for Underdog](https://www.curseforge.com/minecraft/mc-mods/simpledifficulty-for-underdog) (dependency)
>- [Shadowfacts' Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin) (dependency)

**Comment by MagmaSlime123** [comment]
Same issue. I can re-enter the world though.

**Comment by jbredwards** [comment]
fixed the phosphor crash & cascading chunk bugs in v1.8.0
