### ISSUE TITLE
strange behaviour with some modded fluidlogged blocks

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Fluidlogged-API#83]
i have discovered some issues with some modded blocks that id want to be fluidlogged

the first is thermal dynamics servos and other duct attachments on ducts, they appear to be uninterractable when fluidlogged, however they are interractable with a wrench, i just cant open the gui.
https://gfycat.com/harmfulinconsequentialcarpenterant

the second is projectreds cables/wires, they dont properly connect when going round convex corners
https://gfycat.com/FatherlyFlawedCreature

**Comment by jbredwards** [comment]
The ThermalDynamics issue is on their end, it uses a block ray trace to handle player interactions, but it tells the ray trace to stop on fluids (not sure why it does this). Implemented a fix from my end since I doubt the mod is updating 1.12 anymore. I'll investigate the ProjectRed incompat soon, I don't have enough free time rn to learn to read scala

**Comment by xemnes** [comment]
that would be awesome, thank you. yeah sadly the 1.12 version is legacy and they wont be updating it.

**Comment by jbredwards** [comment]
finally figured out how to fix this in v2.0.0!

**Comment by xemnes** [comment]
awesome, thank you!
