### ISSUE TITLE
Lag spikes while placing or breaking blocks underwater

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Fluidlogged-API#86]
Seems like placing or breaking any block underwater (fluidlogged or not) causes lag while testing with only v1.8.0. of this mod installed.

I have a limit of about 60 FPS + VSync and it can get downwards to 18 FPS this way.

**Comment by Rongmario** [comment]
Can't replicate this, do you have a mod list + log file from when this happened?

**Comment by embeddedt** [comment]
I've experienced this when adding Fluidlogged API to my modpack but it seems to go away once enough blocks are placed/broken, so I assume the JIT just needs to kick in.

**Comment by Turkey9002** [comment]
Yeah, I wasn't really specific enough on my post. I meant to say I only tested the game with the API alone without any other mods installed. It also did got a bit better overtime like what was said about enough blocks being placed/broken but I can still feel slight lag spikes. 

I did recorded a video a few minutes ago, I looked at the log too and I wasn't able to find anything other than just the game booting up normally. ^^;

https://user-images.githubusercontent.com/86805568/167915570-e41bfb25-6cbb-4c78-8e3e-90d0c9eacc64.mp4

**Comment by Rongmario** [comment]
10+ chunk updates from placing one block...

**Comment by embeddedt** [comment]
The issue can be reproduced immediately in a dev workspace if you go underwater and place beacons. Here is a spark profile: https://spark.lucko.me/LM6BobaV61

Enabling the Forge `alwaysSetupTerrainOffThread` option hides the issue since it prevents the chunk updates from being completed synchronously.

**Comment by embeddedt** [comment]
This is still an issue as of https://github.com/CleanroomMC/Fluidlogged-API/commit/a0c2fdb92c9835bd2eee808e33e4c9bf81fb65fe, for the record. I think the issue is not specific to blocks being placed underwater (although that seems to exacerbate it), as I discovered placing and breaking a beacon above ground does the same thing. I placed it in a chunk that also contained fluids so that may be related. The lag spikes with Fluidlogged API installed appear to be about twice as tall as those with plain Forge.

**Comment by jbredwards** [comment]
I fixed everything I can relating to this in v1.9.0.0. There's still some render lag (but no server lag anymore), I'm choosing not to fix the render lag since there's already other mods that exist to fix it. Nothirium, Optifine, and VanillaFix are the mods I tested that all fix the render lag, so take your pick :)
