### ISSUE TITLE
Air Bug by 3 Blocks in Minecraft (Trapdoors, Doors and Shulker Boxes)

### ISSUE THREAD

**Issue by Titoo8899** [jbredwards/Fluidlogged-API#88]
Hi,
the new Update 1.8.0 works fantastic and I have no Lags or Crashes. But by 3 Blocks: "Trapdoor, Doors and Shulker Boxes" give it a little Problem or the Waterlogged function and as results give it Air areas. In the Pictures can you see it all. The Doors have a Wall of Air and then we open a Door the Air Wall switch to the other Side. The Shulker Boxes have Air Walls on 2 Sides then we have open it. And the Trapdoor have in the Holes Air and this can we not Waterlogged. I hope with this Pictures can you the Waterlogged Function for this Blocks fixed in next time.

I hope this 4 Pictures help you to fix it in the next Update for a Better Feeling of your Mod. 
![2022-05-11_17 46 16](https://user-images.githubusercontent.com/42325138/167900054-82428109-bce6-4bcc-a556-692623031fae.png)
![2022-05-11_17 47 09](https://user-images.githubusercontent.com/42325138/167900058-d7c31923-63b9-47ad-94b5-8962b25238cf.png)
![2022-05-11_17 47 12](https://user-images.githubusercontent.com/42325138/167900062-25e5f94d-89c5-4cec-a722-0b90cefc580e.png)
![2022-05-11_18 21 40](https://user-images.githubusercontent.com/42325138/167900067-1004ad02-dce9-419c-802a-635e9cdad3ea.png)

P.S. I will in the future your mod with other Mods testet and looks if the compatible to other Mods.

**Comment by Turkey9002** [comment]
Also happens to the beacon too, I assume it happens to all blocks that have transparency.

![2022-05-11_13 12 55](https://user-images.githubusercontent.com/86805568/167918220-4b69ca21-1e72-46bc-a086-7232df7300cd.png)

**Comment by embeddedt** [comment]
This is not a bug for beacons (or is at least a bug in vanilla as well), however the trapdoor issue is valid. See this screenshot from 1.16 for reference.

![image](https://user-images.githubusercontent.com/42941056/167919591-c85b3e59-4b83-463e-9feb-ad544d585b05.png)

**Comment by jbredwards** [comment]
This behavior is intentional, fluids don't connect in situations where they shouldn't. In the waterlogged beacon example Turkey9002 provided, there's glass separating the water inside from the water outside. As for the trap door example provided by embeddedt, 1.16 has a bug where water connects through solid sides, this mod patches that (see [MC-251288](https://bugs.mojang.com/browse/MC-251288)).

**Comment by Titoo8899** [comment]
okay but what is with the Doors and the side of water?

**Comment by jbredwards** [comment]
hmm, the thing with the door in img#3 may be the result of an inconsistency with the fluid renderer. The forge fluid renderer uses boolean IUnlistedProperties to render certain fluids sides from the back. The backs it renders are based on neighboring `getBlockFaceShape` values rather than `canFluidFlow` ones (doors have different values for these two methods). I'll fix the renderer to use canFluidFlow next update

**Comment by Titoo8899** [comment]
ah okay this is good then this one is fix
